apiVersion: v1
kind: Service
metadata:
  name: sample-php-info-svc
  namespace: sit
spec:
  selector:
    app: sample-php-info
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
